#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/../../autoload.php';

use Jug\Command\InitCommand;
use Jug\Command\ServeCommand;
use Jug\Command\BuildCommand;
use Jug\Kernel;
use Symfony\Component\Console\Application;
use Symfony\Component\Filesystem\Filesystem;

$application = new Application();
$filesystem = new Filesystem();
$kernel = new Kernel($filesystem);

$application->add(new BuildCommand($kernel));
$application->add(new ServeCommand($kernel));
$application->add(new InitCommand($filesystem));

$application->run();